---
data_sources:
  main:
    url: <%= ENV["BLAZER_DATABASE_URL"] %>
    smart_variables: 
    linked_columns: 
    smart_columns: 
  newsapp:
    url: mysql2://root:password@localhost:3306/newsapp
  xyz:
    url: mongodb://myuser:mypassword@hostname:27017/mydatabase
audit: true
check_schedules:
- 1 day
- 1 hour
- 5 minutes
